### Introduction to NumPy

**NumPy** (Numerical Python) is a fundamental package for numerical computation in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. NumPy is essential for data science and machine learning, serving as the foundation for many other libraries like Pandas, SciPy, and Scikit-learn.

#### Why use NumPy?

1.  **Performance**: NumPy's core is implemented in C, making it much faster than standard Python lists for numerical operations.
2.  **Memory Efficiency**: NumPy arrays consume less memory compared to Python lists, especially for large datasets.
3.  **Powerful N-dimensional Array Object**: The `ndarray` object is flexible and efficient for storing and manipulating homogeneous data.
4.  **Extensive Mathematical Functions**: It offers a rich set of mathematical functions to perform operations on arrays quickly and efficiently.

### Installation

you can install it using pip. However, if you are using Anaconda distribution, Numpy comes pre-installed in the base environment.

In [2]:
pip install numpy

### Importing NumPy

It's standard practice to import NumPy with the alias `np`.

In [ ]:
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


### NumPy Arrays (ndarray)

The primary object in NumPy is the `ndarray` (N-dimensional array). It's a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.

#### Creating Arrays

1.  **From Python Lists/Tuples**

In [4]:
# 1-D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1-D Array:", arr1)

# 2-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2-D Array:\n", arr2)

# Specifying data type
arr_float = np.array([1, 2, 3], dtype=float)
print("\nArray with float dtype:", arr_float)

1-D Array: [1 2 3 4 5]

2-D Array:
 [[1 2 3]
 [4 5 6]]

Array with float dtype: [1. 2. 3.]


2.  **Using built-in NumPy functions**

In [5]:
# Array of zeros
zeros_arr = np.zeros((3, 4))
print("Array of Zeros:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((2, 3))
print("\nArray of Ones:\n", ones_arr)

# Array with a constant value
full_arr = np.full((2, 2), 7)
print("\nArray with constant value 7:\n", full_arr)

# Identity matrix
identity_mat = np.eye(3)
print("\nIdentity Matrix:\n", identity_mat)

# Array with a range of numbers (like Python's range)
arange_arr = np.arange(0, 10, 2) # start, stop (exclusive), step
print("\nArray from arange:", arange_arr)

# Array with evenly spaced numbers over a specified interval
linspace_arr = np.linspace(0, 1, 5) # start, stop (inclusive), number of elements
print("\nArray from linspace:", linspace_arr)

Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array with constant value 7:
 [[7 7]
 [7 7]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array from arange: [0 2 4 6 8]

Array from linspace: [0.   0.25 0.5  0.75 1.  ]


#### Array Attributes

`ndarray` objects have several useful attributes:

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array:\n", arr)
print("Shape (dimensions):", arr.shape) # (rows, columns)
print("Number of dimensions:", arr.ndim)
print("Total number of elements:", arr.size)
print("Data type of elements:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (dimensions): (3, 3)
Number of dimensions: 2
Total number of elements: 9
Data type of elements: int32
Size of each element in bytes: 4


### Array Indexing and Slicing

Accessing elements or subarrays is similar to Python lists but extended for multiple dimensions.

#### 1-D Arrays

In [7]:
arr = np.arange(10)
print("Array:", arr)

# Accessing a single element
print("Element at index 0:", arr[0])
print("Element at index -1 (last element):", arr[-1])

# Slicing
print("Elements from index 2 to 5 (exclusive):", arr[2:6])
print("Elements from beginning to index 3 (exclusive):", arr[:4])
print("Elements from index 5 to end:", arr[5:])
print("Every other element:", arr[::2])
print("Reversed array:", arr[::-1])

Array: [0 1 2 3 4 5 6 7 8 9]
Element at index 0: 0
Element at index -1 (last element): 9
Elements from index 2 to 5 (exclusive): [2 3 4 5]
Elements from beginning to index 3 (exclusive): [0 1 2 3]
Elements from index 5 to end: [5 6 7 8 9]
Every other element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [8]:
import numpy as np
arr1D = np.array([1,2,3,4,5])
arr2D = np.array([[1,2,3,4],[5,6,7,8]])
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]],[[15,16,17],[19,20,21]]])

print(arr1D.shape)
print(arr2D.shape)
print(arr3D.shape)
print(arr3D)

(5,)
(2, 4)
(3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]

 [[15 16 17]
  [19 20 21]]]


In [10]:
print(arr1D[0])
print(arr2D[1][1])
print(arr3D[1][1][1])
arr1D[:]

1
6
12


array([1, 2, 3, 4, 5])

#### 2-D Arrays (Matrices)

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr)

# Accessing a single element: arr[row, column]
print("Element at (0, 0):", arr[0, 0])
print("Element at (1, 2):", arr[1, 2])

# Accessing a row
print("First row:", arr[0, :]) # or arr[0]

# Accessing a column
print("Second column:", arr[:, 1])

# Slicing rows and columns
print("\nSubarray (first two rows, first two columns):\n", arr[:2, :2])
print("\nSubarray (all rows, last column):\n", arr[:, 2:])

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]

Subarray (first two rows, first two columns):
 [[1 2]
 [4 5]]

Subarray (all rows, last column):
 [[3]
 [6]
 [9]]


In [15]:
num = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(num)
print(num[1:,1:3])
print(num[0:2,2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]
[[3 4]
 [7 8]]


In [21]:
num1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(num1)
print(num1[1:4,1:4])
print(num1[3:,3:])
print(num1[1:4,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[19 20]
 [24 25]]
[[ 8  9]
 [13 14]
 [18 19]]


#### Boolean Indexing

Select elements based on a condition.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original Array:", arr)

# Select elements greater than 30
condition = arr > 30
print("Boolean array (arr > 30):", condition)
print("Elements greater than 30:", arr[condition])

# Combined conditions
print("Elements between 25 and 55:", arr[(arr > 25) & (arr < 55)])

Original Array: [10 20 30 40 50 60]
Boolean array (arr > 30): [False False False  True  True  True]
Elements greater than 30: [40 50 60]
Elements between 25 and 55: [30 40 50]


In [23]:
a = np.array([10,20,30,40,50,60])
print(a>30)
a[a>30]

[False False False  True  True  True]


array([40, 50, 60])

### Basic Array Operations

NumPy allows element-wise operations on arrays.

#### Arithmetic Operations

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + 2)
print("arr1 + arr2:", arr1 + arr2)
print("arr1 - arr2:", arr1 - arr2)
print("arr1 * arr2:", arr1 * arr2) # Element-wise multiplication
print("arr1 / arr2:", arr1 / arr2)
print("arr1 ** 2:", arr1 ** 2) # Element-wise squaring

# Scalar operations
print("arr1 + 10:", arr1 + 10)

[3 4 5]
arr1 + arr2: [5 7 9]
arr1 - arr2: [-3 -3 -3]
arr1 * arr2: [ 4 10 18]
arr1 / arr2: [0.25 0.4  0.5 ]
arr1 ** 2: [1 4 9]
arr1 + 10: [11 12 13]


#### Universal Functions (ufuncs)

NumPy provides many universal functions that operate element-wise on `ndarray` objects.

In [11]:
arr = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Sine:", np.sin(arr))
print("Absolute values:", np.abs(np.array([-1, -2, 3])))
print("Maximum of two arrays:", np.maximum(np.array([1, 5, 2]), np.array([4, 3, 6])))


Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Absolute values: [1 2 3]
Maximum of two arrays: [4 5 6]


#### Aggregation Functions

These functions perform an operation over an array or along a specific axis.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)

print("Sum of all elements:", arr.sum())
print("Mean of all elements:", arr.mean())
print("Maximum element:", arr.max())
print("Minimum element:", arr.min())

# Aggregation along an axis
print("\nSum along columns (axis=0):", arr.sum(axis=0))
print("\nMean along columns (axis=1):", arr.mean(axis=1))
#print(arr.max(axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Mean of all elements: 3.5
Maximum element: 6
Minimum element: 1

Sum along columns (axis=0): [5 7 9]

Mean along columns (axis=1): [2. 5.]
[3 6]


### Advanced NumPy Concepts

#### Reshaping and Transposing Arrays

Changing the shape of an array without changing its data.

In [32]:
arr = np.arange(12)
print("Original 1-D array:", arr)

# Reshape to 3x4 matrix
reshaped_arr = arr.reshape((4, 3))
print("\nReshaped 3x4 array:\n", reshaped_arr)

# Reshape to 2x2x3 3D array
reshaped_3d_arr = arr.reshape((2, 2, 3))
print("\nReshaped 2x2x3 array:\n", reshaped_3d_arr)

# Using -1 to let NumPy infer the dimension
reshaped_auto = arr.reshape((4, -1))
print("\nReshaped 4x-1 array (NumPy infers column count):\n", reshaped_auto)

# Transposing an array (swapping rows and columns)
transposed_arr = reshaped_arr.T
print("\nTransposed array (from 3x4 to 4x3):\n", transposed_arr)

Original 1-D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 3x4 array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped 2x2x3 array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Reshaped 4x-1 array (NumPy infers column count):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Transposed array (from 3x4 to 4x3):
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


#### Concatenation and Splitting Arrays

Joining or dividing arrays.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("arr1:\n", arr1)
print("arr2:\n", arr2)

# Concatenate along rows (axis=0)
concat_rows = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated along rows:\n", concat_rows)

# Concatenate along columns (axis=1)
concat_cols = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along columns:\n", concat_cols)

# Stacking (convenience functions)
vstack_arr = np.vstack((arr1, arr2)) # Stacks vertically (like axis=0)
hstack_arr = np.hstack((arr1, arr2)) # Stacks horizontally (like axis=1)

print("\nVertically stacked:\n", vstack_arr)
print("\nHorizontally stacked:\n", hstack_arr)

# Splitting arrays
long_arr = np.arange(10)
split_arr = np.split(long_arr, [2, 5,8]) # Split before index 2 and before index 5
print("\nOriginal long array:", long_arr)
print("Split array into parts:", split_arr)

arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]

Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Original long array: [0 1 2 3 4 5 6 7 8 9]
Split array into parts: [array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]


#### Broadcasting

Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is 'broadcast' across the larger array so that they have compatible shapes.

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
scalar = 10 # Shape ()

# Scalar is broadcast across the array
print("Array + Scalar:\n", arr + scalar)

vec = np.array([10, 20, 30]) # Shape (3,)

# Vector is broadcast across rows
print("\nArray + Vector (broadcast along rows):\n", arr + vec)

# Example where broadcasting fails due to incompatible shapes
try:
    arr_fail = np.array([[1, 2], [3, 4]]) # Shape (2, 2)
    vec_fail = np.array([10, 20, 30]) # Shape (3,)
    print(arr_fail + vec_fail)
except ValueError as e:
    print(f"\nBroadcasting Error: {e}")

Array + Scalar:
 [[11 12 13]
 [14 15 16]]

Array + Vector (broadcast along rows):
 [[11 22 33]
 [14 25 36]]

Broadcasting Error: operands could not be broadcast together with shapes (2,2) (3,) 


#### Linear Algebra

NumPy is powerful for linear algebra operations.

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Dot product (vector-vector, matrix-vector, matrix-matrix)
# For matrix multiplication, use `@` operator or np.dot()
print("\nMatrix multiplication (A @ B):\n", A @ B)
print("\nMatrix multiplication (np.dot(A, B)):\n", np.dot(A, B))

# Determinant of a matrix
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# Inverse of a matrix
inv_A = np.linalg.inv(A)
print("\nInverse of A:\n", inv_A)

# Check A * A_inv approx Identity matrix
print("\nA @ inv_A:\n", A @ inv_A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]

Matrix multiplication (np.dot(A, B)):
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ inv_A:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


#### Random Number Generation

NumPy's `random` module is extensively used for simulating data, statistical sampling, and machine learning model initialization.

In [31]:
# Generate a single random float between 0.0 and 1.0
print("Single random float:", np.random.rand())

# Generate an array of random floats (uniform distribution)
rand_arr = np.random.rand(3, 2)
print("\nRandom 3x2 array (uniform 0-1):\n", rand_arr)

# Generate an array of random numbers from a standard normal distribution (mean=0, std=1)
randn_arr = np.random.randn(2, 3)
print("\nRandom 2x3 array (standard normal):\n", randn_arr)

# Generate random integers between a low (inclusive) and high (exclusive) value
randint_arr = np.random.randint(low=1, high=10, size=(4))
print("\nRandom integers (1 to 9, size 4):", randint_arr)

# Set a seed for reproducibility
np.random.seed(42)
print("\nRandom number after setting seed 42:", np.random.rand())
#np.random.seed(42) # Set again to get the same sequence
print("Random number after setting seed 42 again:", np.random.rand())


Single random float: 0.7319939418114051

Random 3x2 array (uniform 0-1):
 [[0.59865848 0.15601864]
 [0.15599452 0.05808361]
 [0.86617615 0.60111501]]

Random 2x3 array (standard normal):
 [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]]

Random integers (1 to 9, size 4): [1 3 7 4]

Random number after setting seed 42: 0.3745401188473625
Random number after setting seed 42 again: 0.9507143064099162
